{
 "title": "SAD",
 "time": { "from": "now-45s", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Potential Fraudulent Transactions in the last 10 minutes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from sad.tbl_card_transactions \nwhere potential_fraud = 1 and consumer_tsp >= NOW() - INTERVAL '10 minutes'"
    }
   ]
  },
  {
   "title": "Credit Card Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select card_transaction_id,\n       amount as \"Amount\",\n       consumer_tsp as \"Transaction Time\"\n  from sad.tbl_card_transactions\n order by consumer_tsp desc limit 200;"
    },
    {
     "rawSql": "select \ncard_transaction_id,\ncase \n   when potential_fraud < 1\n   then '#00d989'\n   when potential_fraud >= 1\n   then '#fc1c5b'\n   else '#ff80ed'\nend as \"Mark\",\n consumer_tsp as \"Transaction Time\" \n from sad.tbl_card_transactions order by consumer_tsp desc\nlimit 200;"
    }
   ]
  },
  {
   "title": "Latest Transactios",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "select * from sad.tbl_card_transactions order by consumer_tsp desc limit 200;\n"
    }
   ]
  }
 ]
}