apiVersion: v1
kind: Service
metadata:
  name: consumer-service
  namespace: kafka-predict
  labels:
    app: consumer
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    name: http
  selector:
    app: consumer
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: consumer-ctrl
  namespace: kafka-predict
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer-c
        image: consumer:latest
        imagePullPolicy: IfNotPresent
        command: ["python3"]
        args: ["-u", "./consumer.py"]
